version: '3.8'
services:
  ramble:
    build: .
    image: ramble
    container_name: ramble
    restart: unless-stopped
    environment:
      - RAMBLE_LOAD_FROM_ENV=true
      # Dropbox Configuration
      - DROPBOX_ROOT_FOLDER=/Apps/Ramble
      - DROPBOX_APP_KEY=YOUR_DROPBOX_APP_KEY
      - DROPBOX_APP_SECRET=YOUR_DROPBOX_APP_SECRET
      - DROPBOX_REFRESH_TOKEN=YOUR_DROPBOX_REFRESH_TOKEN
      # - DROPBOX_ACCESS_TOKEN=YOUR_DROPBOX_ACCESS_TOKEN # Uncomment and use if not using OAuth

      # Transcription Configuration
      - TRANSCRIPTION_SERVICE=assemblyai # or openai
      - TRANSCRIPTION_API_KEY=YOUR_TRANSCRIPTION_API_KEY

      # LLM Configuration
      - LLM_SERVICE=anthropic # or openai
      - LLM_API_KEY=YOUR_LLM_API_KEY
      - LLM_MODEL=claude-3-opus-20240229

      # Processing Configuration
      - PROCESSING_COMPRESS_AUDIO=true
      - PROCESSING_COMPRESSION_QUALITY=medium
      - PROCESSING_MAX_FILE_SIZE_MB=100
      - PROCESSING_POLLING_INTERVAL=60
    volumes:
      - ./processed:/app/processed
      - ./logs:/app/logs
