version: '3.8'
services:
  ramble:
    build: .
    container_name: ramble
    restart: unless-stopped
    environment:
      - DROPBOX_ROOT_FOLDER=${DROPBOX_ROOT_FOLDER}
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
      - DROPBOX_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN}
      - TRANSCRIPTION_SERVICE=${TRANSCRIPTION_SERVICE}
      - TRANSCRIPTION_API_KEY=${TRANSCRIPTION_API_KEY}
      - LLM_SERVICE=${LLM_SERVICE}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      - PROCESSING_COMPRESS_AUDIO=${PROCESSING_COMPRESS_AUDIO}
      - PROCESSING_COMPRESSION_QUALITY=${PROCESSING_COMPRESSION_QUALITY}
      - PROCESSING_MAX_FILE_SIZE_MB=${PROCESSING_MAX_FILE_SIZE_MB}
      - PROCESSING_MIN_FILE_SIZE_KB=${PROCESSING_MIN_FILE_SIZE_KB}
      - PROCESSING_POLLING_INTERVAL=${PROCESSING_POLLING_INTERVAL}
    volumes:
      - ./processed:/app/processed
      - ./logs:/app/logs
